- type: gameMapPool
  id: DefaultStarlightMapPool
  maps:
  - StarlightBagel
  - StarlightCog
  - StarlightCork
  - StarlightFland
  - StarlightHotel
  - StarlightLagan
  - StarlightLeth
  - StarlightLobster
  - StarlightManor
  - StarlightMing
  - StarlightOasis
  - StarlightOrigin
  - StarlightOrwell
  - StarlightReach
  - StarlightSaltern
  - StarlightStarboard
  - StarlightKiloton
  - StarlightElkridge
  - StarlightPrism
  - StarlightSilica
  - StarlightCluster
  - StarlightBox
  - StarlightPlasma
  - StarlightPacked
# - StarlightBarratry
