- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 10h
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 10h #yes, chem knowledge is necessary
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 20h #less of a secoff more of a medic
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Medical
  - External
  - Cryogenics
  - Brigmedic
  - Chemistry
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    ears: ClothingHeadsetBrigmedic
    neck: ClothingNeckTieRed
    pocket2: HandheldBrigmedicCrewMonitor
    mask: ClothingMaskBreathMedicalSecurity
    id: BrigmedicPDA
  storage:
    back:
    - Flash
    - SecurityMedkit
    - DefibrillatorBrigmedical

- type: chameleonOutfit
  id: BrigmedicChameleonOutfit
  job: Brigmedic
  equipment:
    mask: ClothingMaskBreathMedicalSecurity
    neck: ClothingNeckTieRed
