using Content.Client.Stylesheets;
using Content.Shared.Chemistry.Reagent;
using Content.Shared._Starlight.Plumbing;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Starlight.Plumbing.UI;

[GenerateTypedNameReferences]
public sealed partial class PlumbingSmartDispenserWindow : DefaultWindow
{
    private const int ReagentRowHeight = 32;

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public event Action<string>? OnDispenseReagentPressed;

    public PlumbingSmartDispenserWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(PlumbingSmartDispenserBuiState state)
    {
        AmountGrid.Selected = ((int) state.SelectedDispenseAmount).ToString();
        UpdateContainerInfo(state);

        _entityManager.TryGetEntity(state.OutputContainerEntity, out var outputContainerEnt);
        View.SetEntity(outputContainerEnt);

        var hasContainer = state.OutputContainer != null;
        ClearButton.Disabled = !hasContainer;
        EjectButton.Disabled = !hasContainer;

        ReagentList.RemoveAllChildren();

        if (state.Entries.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("plumbing-smart-dispenser-empty");
            return;
        }

        var totalVolume = FixedPoint2.Zero;

        foreach (var entry in state.Entries)
        {
            totalVolume += entry.Quantity;

            var chart = BuildReagentRow(entry, state);
            chart.OnChartPressed += reagentId => OnDispenseReagentPressed?.Invoke(reagentId);
            ReagentList.AddChild(chart);
        }

        StatusLabel.Text = Loc.GetString("plumbing-smart-dispenser-total",
            ("total", totalVolume),
            ("count", state.Entries.Count));
    }

    private ClickableBeakerBarChart BuildReagentRow(PlumbingSmartDispenserReagentEntry entry, PlumbingSmartDispenserBuiState state)
    {
        var chart = new ClickableBeakerBarChart
        {
            ReagentId = entry.ReagentId,
            Capacity = state.MaxPerReagent,
            HorizontalExpand = true,
            MinHeight = ReagentRowHeight,
            MaxHeight = ReagentRowHeight,
        };

        chart.Clear();
        chart.SetEntry(
            entry.ReagentId,
            Loc.GetString("plumbing-smart-dispenser-reagent-entry",
                ("reagent", entry.LocalizedName),
                ("amount", entry.Quantity)),
            entry.Quantity.Float(),
            entry.Color,
            tooltip: BuildReagentTooltip(entry, state.MaxPerReagent));

        return chart;
    }

    private string BuildReagentTooltip(PlumbingSmartDispenserReagentEntry entry, float maxPerReagent)
    {
        return Loc.GetString(
            "plumbing-smart-dispenser-row-tooltip",
            ("reagent", entry.LocalizedName),
            ("stored", entry.Quantity),
            ("max", maxPerReagent));
    }

    private void UpdateContainerInfo(PlumbingSmartDispenserBuiState state)
    {
        ContainerInfo.RemoveAllChildren();

        if (state.OutputContainer == null)
        {
            ContainerInfoName.Text = string.Empty;
            ContainerInfoFill.Text = string.Empty;
            ContainerInfo.AddChild(new Label { Text = Loc.GetString("plumbing-smart-dispenser-no-container") });
            return;
        }

        ContainerInfoName.Text = state.OutputContainer.DisplayName;
        ContainerInfoFill.Text = $"{state.OutputContainer.CurrentVolume}/{state.OutputContainer.MaxVolume}u";

        foreach (var (reagent, quantity) in state.OutputContainer.Reagents ?? [])
        {
            var localizedName = _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto)
                ? proto.LocalizedName
                : reagent.Prototype;

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
            };

            row.AddChild(new Label
            {
                Text = $"{localizedName}: ",
            });

            row.AddChild(new Label
            {
                Text = Loc.GetString("reagent-dispenser-window-quantity-label-text", ("quantity", quantity)),
                StyleClasses = { StyleClass.LabelWeak },
            });

            ContainerInfo.AddChild(row);
        }
    }
}
