using Content.Client.Players.PlayTimeTracking;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.Traits;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitEntry : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly JobRequirementsManager _requirementsManager = default!;

    public event Action<bool>? OnToggled;

    public bool IsSelected => TraitCheckbox.Pressed;
    public int TraitCost { get; }

    private readonly TraitPrototype _trait;
    private bool _isUpdating;
    private readonly StripeBack _lockStripe;
    private FormattedMessage requirements = new();

    public TraitEntry(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _trait = trait;
        TraitCost = trait.Cost;

        // Enable mouse events so tooltips work
        MouseFilter = MouseFilterMode.Pass;

        TraitNameLabel.Text = Loc.GetString(trait.Name);
        TraitDescriptionLabel.SetMessage(Loc.GetString(trait.Description));

        // Format cost display
        var costPrefix = trait.Cost > 0 ? "+" : "";
        var costColor = trait.Cost > 0 ? "#ff6b6b" : trait.Cost < 0 ? "#6bff6b" : "#888888";
        TraitCostLabel.Text = $"{costPrefix}{trait.Cost}";
        TraitCostLabel.ModulateSelfOverride = Color.FromHex(costColor);

        TraitCheckbox.OnToggled += OnCheckboxToggled;

        var requirementsLabel = new Label()
        {
            Text = Loc.GetString("role-timer-locked"),
            Visible = true,
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = { StyleClass.LabelSubText },
        };

        _lockStripe = new StripeBack()
        {
            Visible = false,
            HorizontalExpand = true,
            HasMargins = false,
            MouseFilter = MouseFilterMode.Stop,
            Children =
            {
                requirementsLabel
            }
        };

        TraitCheckbox.AddChild(_lockStripe);
    }

    /// <summary>
    /// Updates whether conditions are met based on current job/species.
    /// </summary>
    public void UpdateConditionsMet(HumanoidCharacterProfile? profile)
    {
        MeetsConditions = true;

        if (!_requirementsManager.CheckRequirementsForNonRole(_trait.Requirements, _playerManager.LocalSession, profile, out var reason))
        {
            MeetsConditions = false;
            if (reason is not null)
                requirements = reason;
        }

        UpdateDisabledState();
    }

    private void UpdateDisabledState()
    {
        TraitCheckbox.Disabled = !MeetsConditions;

        if (!MeetsConditions)
        {
            // Deselect if conditions no longer met
            if (TraitCheckbox.Pressed)
            {
                _isUpdating = true;
                TraitCheckbox.Pressed = false;
                UpdateSelectedStyle();
                _isUpdating = false;
                OnToggled?.Invoke(false);
            }

            // Show why it's disabled
            AddStyleClass("TraitsEntryDisabled");

            // Update tooltip to show failed requirements
            var tooltip = new Tooltip();
            tooltip.SetMessage(requirements);
            _lockStripe.TooltipSupplier = _ => tooltip;
            _lockStripe.Visible = true;
        }
        else
        {
            RemoveStyleClass("TraitsEntryDisabled");
            _lockStripe.Visible = false;
        }
    }

    private void OnCheckboxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        if (_isUpdating)
            return;

        if (!MeetsConditions)
        {
            // Prevent selection if conditions not met
            _isUpdating = true;
            TraitCheckbox.Pressed = false;
            _isUpdating = false;
            return;
        }

        UpdateSelectedStyle();
        OnToggled?.Invoke(args.Pressed);
    }

    public void SetSelected(bool selected)
    {
        _isUpdating = true;
        TraitCheckbox.Pressed = selected && MeetsConditions;
        UpdateSelectedStyle();
        _isUpdating = false;
    }

    public bool MeetsConditions { get; private set; } = true;

    private void UpdateSelectedStyle()
    {
        if (TraitCheckbox.Pressed)
            AddStyleClass("TraitsEntrySelected");
        else
            RemoveStyleClass("TraitsEntrySelected");
    }
}