- type: antag
  id: Vampire
  name: roles-antag-vamire-name
  antagonist: true
  setPreference: True # 🌟Starlight🌟
  objective: roles-antag-vampire-description
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20h