- type: gameMapPool
  id: DefaultMapPool
  maps: #Starlight all disabled because they dont exist anymore
  # - Bagel
  # - Box
  # - Elkridge
  # - Fland
  # - Marathon
  # - Oasis
  # - Packed
  # - Plasma
  # - Reach
  # - Exo
  # - Snowball
