- type: job
  id: NanotrasenCareerTrainer
  name: job-name-nct
  description: job-description-nct
  playTimeTracker: JobNanotrasenCareerTrainer
  requirements:
    - !type:RolesRequirement
      proto: StaffAndMentorOnlyRolesReq
  startingGear: NanotrasenCareerTrainerGear
  icon: JobIconNanotrasenCareerTrainer
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-captain
  weight: -1
  overrideConsoleVisibility: false
  canBeAntag: false
  joinNotifyCrew: true
  jobRules: Your job is to try to assist as many crew members as possible regardless of department. You are NOT permitted to give command staff advice on any command SOP questions or aid in legal advice.
  access:
    - Lawyer
    - Command
    - Service
    - Maintenance
    - Theatre
    - External
    - Engineering
    - Research
    - Security
    - Cargo
    - Medical
    - IAA
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]

- type: startingGear
  id: NanotrasenCareerTrainerGear
  equipment:
    id: NanotrasenCareerTrainerPDA
    ears: ClothingHeadsetNCT
    neck: Whistle
    pocket1: nctdatachip
    pocket2: PinpointerUniversal
    belt: BoxFolderNanoTrasenClipboard
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCoatNCT
    suitstorage: WeaponMiniEnergyGun
