- type: antag
  id: Dragon
  name: roles-antag-dragon-name
  antagonist: true
  objective: roles-antag-dragon-objective
  # Starlight start
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 16h
  - !type:RoleTimeRequirement
    role: JobSalvageSpecialist
    time: 6h
  playTimeTracker: AntagDragon
  # Starlight end
