- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: true
  objective: roles-antag-rev-head-objective
  guides: [ Revolutionaries ]
  # Starlight-start
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 72h
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 9h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 12h
  playTimeTracker: AntagHeadRev
  # Starlight-end

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
  guides: [ Revolutionaries ]
  playTimeTracker: AntagRev # Starlight

- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - Flash
    - ClothingEyesGlassesSunglasses
    - USSPUplinkImplanter
