using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Silicons.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AcceptBorgingWindow : DefaultWindow
    {
        public event Action? OnAcceptButtonPressed;
        public event Action? OnDenyButtonPressed;

        public AcceptBorgingWindow()
        {
            RobustXamlLoader.Load(this);
        }

        private readonly AcceptBorgingWindow _window;

        public override void Opened()
        {
            IoCManager.Resolve<IClyde>().RequestWindowAttention();
            _window.OpenCentered();
        }

        public override void Closed()
        {
            _window.Close();
        }

        protected override void Open()
        {
            base.Open();

            _window = this.CreateWindow<AcceptBorgingWindow>();

            _window.OnDenyButtonPressed += () =>
            {
                SendMessage(new AcceptBorgingChoiceMessage(AcceptBorgingUiButton.Deny));
                _window.Close();
            };

            _window.OnClose += () => SendMessage(new AcceptBorgingChoiceMessage(AcceptBorgingUiButton.Deny));

            _window.OnAcceptButtonPressed += () =>
            {
                SendMessage(new AcceptBorgingChoiceMessage(AcceptBorgingUiButton.Accept));
                _window.Close();
            };
        }
    }
}
