- type: entity
  id: CrateServiceHydraRefill
  parent: CratePlastic
  name: hydra refill crate
  description: Contains two refills for the Hydra cleanade launcher.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: MagazineGrenadeCleanade
        amount: 2
