name: Auto Assign Reviewers

on:
- pull_request_target

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Assign reviewers based on labels
        uses: actions/github-script@v7
        with:
          script: |
            const labelToAssign = {
              "Changes: Sprites": ["ss14-Starlight/spriters"],
              "Changes: Map": ["ss14-Starlight/mappers"],
              "Changes: UI": ["ss14-Starlight/dev"],
              "Changes: Shaders": ["ss14-Starlight/dev"],
              "Changes: Audio": ["ss14-Starlight/dev"],
              "Changes: C#": ["ss14-Starlight/dev"],
              "Changes: Prototypes": ["ss14-Starlight/prototypers"],
            };

            const labels = context.payload.pull_request.labels.map(label => label.name);
            const reviewers = new Set();

            for (const label of labels) {
              const tempAssing = labelToAssign[label];
              if (tempAssing) {
                tempAssing.forEach(a => reviewers.add(a));
              }
            }

            if (reviewers.size > 0) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                team_reviewers: Array.from(reviewers),
              });
            }
