using System.Linq;
using Content.Client.Options.UI;
using Content.Client.UserInterface.Screens;
using Content.Shared._Starlight.CombatMode;
using Content.Shared.CCVar;
using Content.Shared.HUD;
using Content.Shared.Starlight.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class UITab : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public UITab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var themes = _prototypeManager.EnumeratePrototypes<HudThemePrototype>().ToList();
        themes.Sort();
        var themeEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var gear in themes)
        {
            themeEntries.Add(new OptionDropDownCVar<string>.ValueOption(gear.ID, Loc.GetString(gear.Name)));
        }

        var layoutEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var layout in Enum.GetValues(typeof(ScreenType)))
        {
            layoutEntries.Add(new OptionDropDownCVar<string>.ValueOption(layout.ToString()!, Loc.GetString($"ui-options-hud-layout-{layout.ToString()!.ToLower()}")));
        }

        var rangedSights = new List<OptionDropDownCVar<string>.ValueOption>();
        var meleeSights = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var sight in _prototypeManager.EnumeratePrototypes<SightPrototype>())
        {
            var option = new OptionDropDownCVar<string>.ValueOption(sight.ID, Loc.GetString(sight.Name));
            if (sight.Bolt)
                continue;
            switch (sight.SightType)
            {
                case SightType.Ranged:
                    rangedSights.Add(option);
                    break;
                case SightType.Melee:
                    meleeSights.Add(option);
                    break;
                case SightType.Universal:
                    meleeSights.Add(option);
                    rangedSights.Add(option);
                    break;
            }
        }

        SightsOptionsHash.OnTextChanged += OnTextChanged;
        UpdateSightsOptionsHash();
        _cfg.OnValueChanged(StarlightCCVars.RangedSight, _ => UpdateSightsOptionsHash(), true);
        _cfg.OnValueChanged(StarlightCCVars.MeleeSight, _ => UpdateSightsOptionsHash(), true);
        _cfg.OnValueChanged(StarlightCCVars.RangedSightScale, _ => UpdateSightsOptionsHash(), true);
        _cfg.OnValueChanged(StarlightCCVars.RangedSightOffset, _ => UpdateSightsOptionsHash(), true);
        _cfg.OnValueChanged(StarlightCCVars.SightMainColor, _ => UpdateSightsOptionsHash(), true);
        _cfg.OnValueChanged(StarlightCCVars.SightSecondColor, _ => UpdateSightsOptionsHash(), true);

        Control.AddOptionDropDown(CVars.InterfaceTheme, DropDownHudTheme, themeEntries);
        Control.AddOptionDropDown(CCVars.UILayout, DropDownHudLayout, layoutEntries);
        Control.AddOptionSlider(StarlightCCVars.ChatSeparatedMinWidth, SeparatedChatWidthSlider, 300, 580);
        Control.AddOptionDropDown(StarlightCCVars.RangedSight, DropDownRangedSight, rangedSights);
        Control.AddOptionDropDown(StarlightCCVars.MeleeSight, DropDownMeleeSight, meleeSights);
        Control.AddOptionSlider(StarlightCCVars.RangedSightScale, RangedSightScaleSlider, 10, 100);
        Control.AddOptionSlider(StarlightCCVars.RangedSightOffset, RangedSightOffsetSlider, 0, 100);
        Control.AddOptionColorSlider(StarlightCCVars.SightMainColor, SightMainColorSlider);
        Control.AddOptionColorSlider(StarlightCCVars.SightSecondColor, SightSecondColorSlider);
    }

    private void UpdateSightsOptionsHash()
    {
        var ranged = _cfg.GetCVar(StarlightCCVars.RangedSight);
        var melee = _cfg.GetCVar(StarlightCCVars.MeleeSight);
        var scale = _cfg.GetCVar(StarlightCCVars.RangedSightScale);
        var offset = _cfg.GetCVar(StarlightCCVars.RangedSightOffset);
        var main = _cfg.GetCVar(StarlightCCVars.SightMainColor);
        var second = _cfg.GetCVar(StarlightCCVars.SightSecondColor);
        var raw = $"{ranged}\u001F{melee}\u001F{scale}\u001F{offset}\u001F{main}\u001F{second}";
        var bytes = System.Text.Encoding.UTF8.GetBytes(raw);
        var packed = Convert.ToBase64String(bytes);
        SightsOptionsHash.Text = packed;
        SightsOptionsHash.UpdateDraw();
    }

    private void OnTextChanged(LineEdit.LineEditEventArgs args)
    {
        if (args.Text.ToString() is not string packed)
            return;
        byte[] bytes = [];
        try
        {
            bytes = Convert.FromBase64String(packed);
        }
        catch
        {
            return;
        }
        var raw = System.Text.Encoding.UTF8.GetString(bytes);
        var parts = raw.Split('\u001F');

        if (parts.Length != 6)
            return;

        if (_prototypeManager.TryIndex(parts[0], out SightPrototype? ranged) && ranged.SightType is (SightType.Ranged or SightType.Universal))
            _cfg.SetCVar(StarlightCCVars.RangedSight, parts[0], true);

        if (_prototypeManager.TryIndex(parts[1], out SightPrototype? melee) && melee.SightType is (SightType.Melee or SightType.Universal))
            _cfg.SetCVar(StarlightCCVars.MeleeSight, parts[1], true);

        if (int.TryParse(parts[2], out var scale))
            _cfg.SetCVar(StarlightCCVars.RangedSightScale, scale, true);
        if (int.TryParse(parts[3], out var offset))
            _cfg.SetCVar(StarlightCCVars.RangedSightOffset, offset, true);

        if (Color.TryFromHex(parts[4]) != null)
            _cfg.SetCVar(StarlightCCVars.SightMainColor, parts[4], true);

        if (Color.TryFromHex(parts[5]) != null)
            _cfg.SetCVar(StarlightCCVars.SightSecondColor, parts[5], true);
    }
}